### ISSUE TITLE
Tests failing on windows

### ISSUE THREAD

**Issue by Acconut** [sydneystockholm/ferguson#3]
Most of the tests are failing on Window because of its "inconsistencies to unix":
Paths use the backslash, e.g. "\asset-blsavdw4g453gf-style.css" while the tests except the frontslash.

I wouldn't recommend fixing those but there should be a note somewhere in the README.

**Comment by jbergstroem** [comment]
Going to close this based on inactivity. Since neither of us "devs" have access to a windows machine, we can't do much. Feel free to reopen or create a new PR if there's code to be contributed.
